### ISSUE TITLE
On version 1.18, barrels do not spawn below 0 height

### ISSUE THREAD

**Issue by Aeon2927** [Tallcraft/DeathBarrel#17]
On version 1.18, barrels do not spawn below 0 height

**Comment by Aeon2927** [comment]
Clarification. They spawn in an empty space above 0

**Comment by Trikolon** [comment]
@Aeon2927 Thanks for the bug report. Could you please try this dev-build and see if it fixes the issue for you?
https://github.com/Tallcraft/DeathBarrel/suites/4545612080/artifacts/121945537

**Comment by Aeon2927** [comment]
Now it’s ok. Spawned at -63
