### ISSUE TITLE
Suggestion: Barrel skin + limit max barrels per player

### ISSUE THREAD

**Issue by Espinete87** [Tallcraft/DeathBarrel#8]
Hello Tallcraft, i would like to know if you can implement a option in config to let us choose the skin of the barrel, for example i want a backpack, or maybe other people want a metal box so... that could be really nice.

Second is, can you add a option to choose how many barrels a person can create? Thats quite important, more than cool is needed, you know how messy an become the server with many players hehe.

Thanks!

**Comment by Trikolon** [comment]
I currently don't see a simple way to implement custom textures for barrels.

For the second suggestion I've created a separate issue #9
